version: "3.3"
services:
  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: hasura
    restart: always
    ports:
    - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@47.100.92.188:5432/cloudauth
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"jwtsecret of 32 characters or more"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  pgdb_init:
